version: '3.8'

services:
  client:
    build: ./client
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.20
    env_file:
      - .env
    environment:
      - IFS_REDIS_HOST=redis
      - IFS_REDIS_PASSWORD=${REDIS_PASSWORD}
      - IFS_MONGODB_HOST=mongodb
      - IFS_MONGODB_USERNAME=${MONGO_USER_USERNAME}
      - IFS_MONGODB_PASSWORD=${MONGO_USER_PASSWORD}
    depends_on:
      - mongodb
      - redis
      - influxdb
    ports:
      - "5000:5000"

  ifs:
    build: ./ifs
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.20
      wannetwork:
        ipv4_address: 10.1.0.2
    env_file:
      - .env
    environment:
      - IFS_REDIS_HOST=redis
      - IFS_REDIS_PASSWORD=${REDIS_PASSWORD}
      - IFS_MONGODB_HOST=mongodb
      - IFS_MONGODB_USERNAME=${MONGO_USER_USERNAME}
      - IFS_MONGODB_PASSWORD=${MONGO_USER_PASSWORD}
    depends_on:
      - mongodb
      - redis
      - influxdb

  #simulated gateway for testing
  test_gateway:
    build: ./test_gateway
    networks:
      wannetwork:
        ipv4_address: 10.1.0.10


  static_dataprovider:
    build: ./static_dataprovider
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.10
    env_file:
      - .env
    environment:
      - IFS_REDIS_HOST=redis
      - IFS_REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - influxdb
      - redis

  solver:
    build: ./solver
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.11
    env_file:
      - .env
    environment:
      - IFS_REDIS_HOST=redis
      - IFS_REDIS_PASSWORD=${REDIS_PASSWORD}
      - IFS_MONGODB_HOST=mongodb
      - IFS_MONGODB_USERNAME=${MONGO_USER_USERNAME}
      - IFS_MONGODB_PASSWORD=${MONGO_USER_PASSWORD}
    depends_on:
      - mongodb
      - influxdb
      - redis


# mongodb as persistent scada database
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.5
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: scada
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME} # replicaset is needed for changestreams
    ports:
      - "27017:27017"
    volumes: #WARNING: mongodb.key needs to be chmod 400 and chown 999:999 to work like this
      - ./mongodb/mongodb.key:/data/mongodb.key
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ["--keyFile", "/data/mongodb.key", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]

# redis as real-time database
  redis:
    image: "redis:alpine"
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.6
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --notify-keyspace-events K$$
    ports:
      - "6379:6379"

# management interface for mongodb
  admin-mongo:
    image: mongo-express
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.30
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/?replicaSet=${MONGO_REPLICA_SET_NAME}
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb
    depends_on:
      - mongodb

# management interface for redis
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.31
    env_file:
      - .env
    environment:
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
    - "8082:8081"

# timeseries db
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.7
    env_file:
      - .env
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
    #USER = admin, PASSWORD = administrator

# timeseries dashboard, username:admin, password: admin
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.8
    env_file:
      - .env
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana

# manage containers, password is Administrator
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      scadanetwork:
        ipv4_address: 10.2.0.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


volumes:
  portainer_data:

networks:
  scadanetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

  wannetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
